truncate table tb_catnombramientos;

insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ABOGADO A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ABOGADO B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ABOGADO C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ADMINISTRADOR A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ADMINISTRADOR B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ADMINISTRADOR ESPECIALIZADO A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ANALISTA A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ANALISTA AA""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ANALISTA B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ANALISTA C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ANALISTA DE PROYECTOS',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ARCHIVISTA LOCALIZADOR',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ASESOR A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ASISTENTE A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ASISTENTE B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ASISTENTE C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ASISTENTE DE DIRECTOR',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('AUXILIAR ADMINISTRATIVO A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('AUXILIAR DE SERVICIOS C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('AUXILIAR OPERATIVO A""',2,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('AUXILIAR TECNICO A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('AUXILIAR TECNICO B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('AUXILIAR TECNICO C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('BECARIO',2,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COMISARIO',1,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('CONSULTOR',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('DIR. JURIDICO DE SEG. CIUDADANA',2,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('DIRECTOR A',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('DIRECTOR B',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('DIRECTOR C',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ESCRIBIENTE',2,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('INSPECTOR',1,1,8, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('INSTRUCTOR A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('INSTRUCTOR AA""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE DEPARTAMENTO',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE DEPARTAMENTO A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE DEPARTAMENTO B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE OFICINA ',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE OFICINA A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE PISO',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE SECCION  A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE SECCION  B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE TURNO',2,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE UNIDAD DEPTAL  B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE SECCION',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE UNIDAD DEPTAL. A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('OFICIAL',2,1,6, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('OFICIAL DE SERVICIOS C""',2,1,null, 0); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('PILOTO',2,1,null, 0); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('POLICIA',2,1,1, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('POLICIA PRIMERO',2,1,4, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('POLICIA SEGUNDO',2,1,3, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('POLICIA TERCERO',2,1,2, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('PROYECTISTA',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('PSICOLOGO',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SECRETARIA A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SECRETARIA B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SOPORTE TECNICO A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SOPORTE TECNICO B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SOPORTE TECNICO ESPECIALIZADO B',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SOPORTE TECNICO ESPECIALIZADO C',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SUB-INSPECTOR',1,1,7, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SUB-OFICIAL',2,1,5, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SUPERVISOR A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SUPERVISOR B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SUPERVISOR C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SUPERVISOR DE CONTROL DE CALIDAD',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SUPERVISOR MULTIFUNCIONAL',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('TECNICO ESPECIALIZADO',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SOPORTE TECNICO C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('TECNICO ESPECIALIZADO A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('TECNICO OPERATIVO ESPECIA',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('TRABAJADOR SOCIAL A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('TRABAJADOR SOCIAL AA""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('VIGILANTE INTERNO',2,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('TECNICO A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('TECNICO C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SUPERVISOR ANALISTA',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE AREA',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COMANDANTE 1RO',2,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COMANDANTE 2DO',2,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COMANDANTE 3RO',2,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('INSPECTOR OPERATIVO 1503',2,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('OMEGA',2,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('DELTA',2,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COORDINADOR OPERATIVO 1504',2,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('DIRECTOR OPERATIVO 1502',2,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ALMACENISTA',2,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ANALISTA DE RECACCIÓN',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ASESOR ESPECIALIZADO',2,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('AUXILIAR ADMINISTRATIVO B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('AUXILIAR ADMINISTRATIVO AA""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('AUXILIAR DE INTENDENCIA A""',2,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COLABORADOR A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COLABORADOR AA""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('MEDICO GENERAL',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COLABORADOR B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COLABORADOR C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('OFICIAL AYUDANTE 1RO',2,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('OFICIAL AYUDANTE 2DO',2,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('OFICIAL AYUDANTE 3RO',2,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE DEPARTAMENTO C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COORDINADOR',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('AUXILIAR ADMINISTRATIVO C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('LIDER DE PROYECTOS',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SUPERVISOR GENERAL',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SECRETARIA AA""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COLABORADOR D""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COLABORADOR E""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COMANDANTE',2,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('MEDICO ESPECIALISTA B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('MEDICO ESPECIALISTA C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('113',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('MEDICO GENERAL C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('TECNICO ESPECIALIZADO B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('TECNICO ESPECIALIZADO C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('OFICIAL DE SERVICIOS A""',2,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ESCOLTA',2,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ADMINISTRADOR ESPECIALIZADO B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('CHOFER A',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ADMINISTRADOR C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('OFICIAL',1,1,null, 1); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE UNIDAD DEPARTAMENTAL',null,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE UNIDAD DEPARTAMENTAL C""',null,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SUPERVISOR ESPECIALIZADO B""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ANALISTA DE RECURSOS MATERIALES',null,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('JEFE DE ORGANIZACIÓN Y MÉTODOS',null,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ENCARGADO DE ALMACEN',null,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SECRETARIO TECNICO',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SUPERVISOR ESPECIALIZADO A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('SUPERVISOR ESPECIALIZADO C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COLABORADOR ESPECIALIZADO A""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('AUXILIAR DE MTTO, DE AREAS VERDES',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('OPERARIO DE SACRIFICIO C""',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('ADMINISTRADOR DE TIANGUIS',1,1,null, null); 
insert into tb_catnombramientos (nombre, tipo, estado, nivel, operativo) values ('COTIZADOR',1,1,null, null); 
