select * from tb_departamentos;
truncate table tb_departamentos;

insert into tb_departamentos(nombre,estado,operativo) values ('TECNOLOGÍAS DE LA INFORMACIÓN',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE VEHICULOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('RECURSOS HUMANOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('SERVICIOS EXTRAORDINARIOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('FORTASEG',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CONTROL PRESUPUESTAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE SALUD EN EL TRABAJO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('JEFATURA DE SERVICIOS GENERALES',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE AUDITORIA INTERNA Y CONTROL DE PROCESOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ADMINISTRATIVA',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('SUPERVISION DE ZONAS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ACREDITACION DE PROCESOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE ESTADÍSTICA Y GEOMATICA DEL DELITO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UIPD',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ZONA1A',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ZONA1B',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ZONA2A',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ZONA2B',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ZONA3',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ZONA4',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ZONA5A',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ZONA5B',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ZONA6',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ZONA7A',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ZONA7B',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CECOE',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CENTRO HISTORICO',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('OFICIALIA DE CUARTEL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('OLIMPOS',0,1);
insert into tb_departamentos(nombre,estado,operativo) values ('SUPERVISION GENERAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('SEUZ',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UREDES',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE EQUIPAMIENTO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCION DE LA ACADEMIA DE FORMACIÓN Y PROFESIONALIZACIÓN POLICIAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CABINA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD INTEGRAL DE CRIMINALISTICA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('U.R.S.E',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE  PREVENCION ESCOLAR',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ACTIVIDADES DEPORTIVAS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('FUERZAS SEGURIDAD CIUDADANA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('COSMOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DESPACHO DE COMISARIO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCION DE LO JURÍDICO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIVISIÓN OPERATIVA',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCION DE EVALUACION Y SEGUIMIENTO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('GAMAS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ZONA CENTRO',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD ZEUS ',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('COMISARIA DE INTELIGENCIA (UIPD)',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('PRESIDENCIA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('TEDAX',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('U.R.E.P.A.Z',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCION GENERAL DEL AYUNTAMIENTO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCIÓN COMUNICACIÓN SOCIAL Y RELACIONES PUBLICAS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('SINDICATURA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('SUB UNIDAD K9',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('INSPECCION Y VIGILANCIA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('JUSTICIA MUNICIPAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('EVALUACION Y SEGUIMIENTO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIVISIÓN DE VINCULACIÓN CIUDADANA Y PREVENCIÓN SOCIAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCION ENLACE ADMINISTRATIVO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('U.R.E.D.E.S',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('SALUD MENTAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('BIBLIOTECA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DEFENDER',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('U.P.R.E.S',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('PREVENCION SOCIAL DEL AYUNTAMIENTO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CAPACITACION Y DESARROLLO HUMANO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DESARROLLO INSTITUCIONAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('PAGOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DEPOSITO DE ARMAMENTO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE RECLUTAMIENTO Y SELECCION DE PERSONAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('SINDICATO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ARCHIVO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CONTROL Y SANCIONES',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE ARMAMENTO MUNICIONES Y EQUIPO POLICIAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('COMISARÍA DE LA DIVISIÓN DE PLANEACIÓN Y GESTIÓN ESTRATÉGICA',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('LICENCIA COLECTIVA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('PRENSA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('RELACIONES PUBLICAS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CONTROL DE PERSONAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CONTROL DE INVENTARIOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('MANTENIMIENTO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('SECRETARÍA TÉCNICA DE COMISIÓN MINICIPAL DE CARRERA POLICIAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DERECHOS HUMANOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ENLACE TRANSPARENCIA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('GUARDIAS MUNICIPALES',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UBICACIÓN DESCONOCIDA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('RADIOCOMUNICACIONES',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('AREA DE APOYO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIR. ADMVA. BOMBEROS Y PROT. CIVIL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('PROMOCION A LA SALUD (GIMNASIO)',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIR. TECNICA DE INSPECCION',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('RECURSOS HUMANOS DEL AYUNTAMIENTO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('FUERZA UNICA METROPOLITANA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('BIENES PATRIMONIALES	',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('JUZGADOS MUNICIPALES	',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('TALLER PATRIA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('OFICIALIA MAYOR',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('OFICIALIA DE PARTES',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ENLACE INSTITUCIONAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CALEA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('AGENCIA DE ATENCION DE DENUNCIAS CIUDADANAS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ASUNTOS INTERNOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('INFORMACION Y DISEÑO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('PERFILES',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CICLOS',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCIÓN DE ASESORES',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIVISIÓN DE LOGÍSTICA',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE ANALISIS DE LA INFORMACIÓN (U.D.A.I)',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE INVESTIGACIÓN',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('OFICINA DE AUTOS CIVILES',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE INTELIGENCIA (UDI)',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UPYP',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ENLACE DE FONDOS Y SUBSIDIOS FEDERALES',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIVISION DE INTELIGENCIA',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('DIVISION DE OPERACIONES REGION 01',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIVISION DE OPERACIONES REGION 02',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIVISION DE OPERACIONES REGION 03',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIVISION DE AGRUPAMIENTOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('REGIDORES',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('COMISIONADO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE DOCTRINA POLICIAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE PREVENCION SOCIAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CENTRO INTEGRAL DE ATENCIÓN CIUDADANA STA CECILIA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ALMACEN GENERAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('POLIGONO01',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('POLIGONO02',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('POLIGONO03',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('POLIGONO04',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('POLIGONO05',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('POLIGONO06',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('POLIGONO07',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('POLIGONO08',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('POLIGONO09',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('POLIGONO10',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE DISEÑO DE OPERATIVOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('BANDA DE GUERRA (OLIMPOS)',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('SUB UNIDAD ESPECIALIZADA AEROTACTICA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('TECNOLOGIAS DE LA INFORMACIÓN CECOE',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('GRUPO O.C.R.A',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CONTRATOS DEA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('FISCALÍA GENERAL DEL ESTADO DE JALISCO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('RECURSOS MATERIALES DEL AYUNTAMIENTO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCIÓN DE LA ACADEMIA DE FORMACIÓN',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CAFETERÍA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('COORDINACIÓN DE DISCAPACIDAD Y REINCORPORACIÓN LABORAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('EVALUACIÓN MEDICA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CONTRALORÍA CIUDADANA (GOBIERNO MUNICIPAL)',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('TIANGUIS Y COMERCIO (AYUNTAMIENTO)',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE LA DIVISIÓN DE CARRERA POLICIAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ADMINISTARCIÓN DIVISIÓN OPERATIVA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD CENTRO DE MANDO MAVIL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCIÓN DE ADQUISIONES DEL AYUNTAMIENTO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('GRUPO BENGALAS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE CONTROL DE INSIDENCIAS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE INFRAESTRUCTURA Y DATOS DIRECCIÓN DE INNOVACION GUBERNAMENTAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('COMISARÍA MUNICIPIO FORANEO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ASUNTOS INTERNOS DEL HAYUNTAMIENTO DE GUADALAJARA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DEPOSITO VEHÍCULAR	',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('IJAS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('R.R.S DIGITAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ADMINISTRACIÓN DEL DESPACHO DEL COMISARIO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('VISITADOR GENERAL DEL COMISÍON ESTATAL DE DERECHOS HUMANOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('SECRETARIA PARTICULAR',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('SECRETARIA GENERAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('JUZGADOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('FUERZAS DE REACCIÓN INMEDIATA MIXTA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CAMARA DE COMERCIO DE GUADALAJARA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('SECRETARIA GENERAL DE GOBIERNO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCIÓN DE ADMINISTRACION DEL AYUNTAMIENTO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCIÓN GENERAL JURÍDICA MUNICIPAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('MEDIO AMBIENTE GESTIÓN INTEGRAL DE LA CIUDAD',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('COMUDE',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('TRABAJO SOCIAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('PROCURADURIA GENERAL DE LA REPUBLICA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCION GENERAL JURIDICA MUNICIPAL',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('COMISION MUNICIPAL DE HONOR Y JUSTICIA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('1503 ALFA COMISARIA DE AGRUPAMIENTOS',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('1503 DELTA COMISARIA REGIONAL (REGION UNO)',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('1503 GAMA COMISARIA REGIONAL (REGION DOS)',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('1503 BETA COMISARIA REGIONAL (REGION TRES)',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('COMANDANCIA REGIONAL DE SUPERVISION POLIGONO01',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('COMANDANCIA REGIONAL DE SUPERVISION POLIGONO02',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('COMANDANCIA REGIONAL DE SUPERVISION POLIGONO03',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('COMANDANCIA REGIONAL DE SUPERVISION POLIGONO04',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('COMANDANCIA REGIONAL DE SUPERVISION POLIGONO05',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('COMANDANCIA REGIONAL DE SUPERVISION POLIGONO06',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('COMANDANCIA REGIONAL DE SUPERVISION POLIGONO07',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('COMANDANCIA REGIONAL DE SUPERVISION POLIGONO08',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('COMANDANCIA REGIONAL DE SUPERVISION POLIGONO09',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('COMANDANCIA REGIONAL DE SUPERVISION POLIGONO10',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('AUXILIAR DE SUPERVISION POSEIDON01',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('AUXILIAR DE SUPERVISION POSEIDON02',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('AUXILIAR DE SUPERVISION POSEIDON03',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD PARA LA DEFENSORIA DE LOS DERECHOS DE LOS POLICIAS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE EVALUACION Y CONTROL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('INSTITUTO MEXICANO DEL SEGURO SOCIAL IMSS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('INTERESADO (A) (OS) (AS)',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('PRESIDENCIA MUNICIPAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('PROMOTORA DE FUTBOL ROJINEGROS SA DE CV',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('PATRONATO LEONES NEGROS UNIVERSIDAD DE GUADALAJARA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('SECRETARIO PARTICULAR DEL PRESIDENTE MUNICIPAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CONSEJO MUNICIPAL DEL DEPORTE (COMUDE)',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCION GENERAL DE CODE JALISCO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCION DE INSPECCION A REGLAMENTOS Y ESPECTACULOS',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('PRESIDENCIA CAMARA DE JOYERIA DE JALISCO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCION DE MOVILIDAD Y TRANSPORTE DEL MUNICIPIO DE GUADALAJARA',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE PLANEACIÓN',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DE INOVACIÓN Y ACREDITACIÓN DE PROCESOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DESPACHO DEL COMISARIO JEFE',1,1);
insert into tb_departamentos(nombre,estado,operativo) values ('INSTITUCIONES EDUCATIVAS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('COORDINACIÓN GENERAL DE SERVICIOS MUNICIPALES',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCIÓN GENERAL DEL CONSEJO MUNICIPAL DEL DEPORTE DE GUADALAJARA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('SECRETARIO EJECUTIVO DEL CONSEJO ESTATAL DE SEGURIDAD PUBLICA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCIÓN DE ADMINISTRACIÓN MUNICIPAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DIRECCIÓN DE PATRIMONIO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DEPARTAMENTO DE MUEBLES',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ADMINISTRACIÓN DE LO JURÃDICO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ACTAS ADMINISTRATIVAS CTRO Y CONFIANZA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('AMPAROS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ARMAMENTO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CONTENCIOSO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('DERECHOS HUMANOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ORION',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('PENAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('PENAL ORION',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('PENAL Y ARMAMENTO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('TRANSPARENCIA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('VEHÍCULOS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('TURSIMO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('JEFATURA DE GABINETE',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('FISCALIA GENERAL DE LA REPÚBLICA',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CÁMARA DE JOYERÍA JALISCO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('C5',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CLUB ATLAS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('PROTECCIÓN CIVIL Y BOMBEROS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ADMINISTRACIÓN E INNOVACIÓN GUBERNAMENTAL',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('JEFATURA DE TECNOLOGÍAS DE LA INFORMACIÓN',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CENTRO DE JUSTICIA PENAL FEDERAL DEL ESTADO DE JALISCO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('COORDINACIÓN GENERAL ESTRATÉGICA DE SEGURIDAD',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('CONTROL Y MANTENIMIENTO DE VEHICULOS CICLOS Y SEGWAY',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('API 2020',0,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('API 2020',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('UNIDAD DEPARTAMENTAL DE SERVICIOS GENERALES DEL AYUNTAMIENTO',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('ESTAFETAS',1,NULL);
insert into tb_departamentos(nombre,estado,operativo) values ('AREA LEGAL DE RECURSOS HUMANOS',1,NULL);
