CREATE TABLE `tb_armas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `numero_servicio` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `abogado_integrado` int(11) DEFAULT NULL,
  `estado` int(11) NOT NULL,
  `numero_expediente` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `poligono` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `solicitante` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `encargado` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `fecha_registro` timestamp NOT NULL,
  `motivo_investigacion` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ofendido` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `fecha_resolucion` timestamp NOT NULL,
  `sentido_resolucion` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `estado_procesal` int(11) NOT NULL,
  `activo` tinyint(1) DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `tb_armas_estado_procesal_foreign` (`estado_procesal`),
  KEY `tb_armas_estado_foreign` (`estado`),
  CONSTRAINT `tb_armas_estado_foreign` FOREIGN KEY (`estado`) REFERENCES `tb_estados` (`id`),
  CONSTRAINT `tb_armas_estado_procesal_foreign` FOREIGN KEY (`estado_procesal`) REFERENCES `tb_catestadosprocesales` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
