CREATE TABLE `tb_agenciasvarias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`carpetaAdministrativa` VARCHAR(50) NULL DEFAULT NULL,
	`carpetaInvestigacion` VARCHAR(50) NULL DEFAULT NULL,
	`averiguacionPrevia` VARCHAR(50) NULL DEFAULT NULL,
	`expediente` VARCHAR(50) NULL DEFAULT NULL,
	`fechaAsignacion` DATETIME NULL DEFAULT NULL,
	`civil` VARCHAR(50) NULL DEFAULT NULL,
	`policia` VARCHAR(50) NULL DEFAULT NULL,
	`activo` TINYINT(4) NULL DEFAULT '1',
	`observaciones` VARCHAR(100) NULL DEFAULT NULL,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB