CREATE TABLE `tb_contratosyconvenios` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`ObjetoContrato` VARCHAR(50) NULL DEFAULT NULL,
	`Contratante` VARCHAR(50) NULL DEFAULT NULL,
	`Vigencia` DATETIME NULL DEFAULT NULL,
	`FundamentoLegal` VARCHAR(50) NULL DEFAULT NULL,
	`Recurso` VARCHAR(50) NULL DEFAULT NULL,
	`ContraPrestacion` VARCHAR(50) NULL DEFAULT NULL,
	`Decreto` VARCHAR(50) NULL DEFAULT NULL,
	`FechaElaboracion` DATETIME NULL DEFAULT NULL,
	`Tipo` INT(11) NULL DEFAULT NULL,
	`Activo` TINYINT(4) NULL DEFAULT '1',
	`Observacion` TEXT NULL,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB