CREATE TABLE `tb_estados` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`estado` VARCHAR(50) NOT NULL DEFAULT 'activo',
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB