CREATE TABLE `tb_tipocontrato` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Tipo` VARCHAR(35) NULL DEFAULT NULL,
	`create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`Id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB